name: "Check Formats"
runs:
  using: "composite"
  steps:
    - name: Check File Format
      run: |
          export BRANCH_NAME=origin/${{ github.event.repository.default_branch }}
          ./scripts/githooks/editorconfig-pre-commit.sh
    
    - name: Check Markdown Format
      run: |
          export BRANCH_NAME=origin/${{ github.event.repository.default_branch }}
          ./scripts/githooks/markdown-pre-commit.sh
