name: Release

on:
    workflow_dispatch:
        inputs:
            release_version:
                type: string
                description: The version to release
                required: true
            
            prerelease:
                type: boolean
                description: Mark release as pre-release
                default: false

jobs:
    build_cloudfront_logs_lambda:
        name: Build CloudFront Logs Lambda for Node.js v${{ matrix.nodejs_version }}
        runs-on: ubuntu-latest

        strategy:
            matrix:
                nodejs_version: ["14.x", "16.x", "18.x"]

        steps:
            - uses: actions/checkout@v3
            
            - uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.nodejs_version }}
                cache: yarn
                cache-dependency-path: modules/cloudfront-logs/lambda/yarn.lock

            - name: Install Dependencies
              run: make install-cloudfront-logs-lambda
            
            - name: Build Lambda
              run: make build-cloudfront-logs-lambda
            
            - name: Copy Lambda Asset
              run: cp modules/cloudfront-logs/lambda/dist/lambda.zip cloudfront-logs-package-${{ inputs.release_version }}-nodejs${{ matrix.nodejs_version }}.zip
            
            - name: Store Output Artifact
              uses: actions/upload-artifact@v3
              with:
                name: cloudfront-logs-packages
                path: cloudfront-logs-package-${{ inputs.release_version }}-nodejs${{ matrix.nodejs_version }}.zip
                if-no-files-found: error