name: Release
run-name: Publish Release Version ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*"

jobs:
  get_metadata:
    name: Get Metadata
    runs-on: ubuntu-latest
    outputs:
      prerelease: ${{ steps.determine_prerelease.outputs == 'true' }}

    steps:
      - name: Determine if prerelease
        id: determine_prerelease
        run: |
            if [[ "${{ github.ref_name }}" =~ ^v[0-9]*\.[0-9]*\.[0-9]*-.*?\.[0-9]*? ]]; then
              echo "prerelease=true" >> "$GITHUB_OUTPUT"
            else
              echo "prerelease=false" >> "$GITHUB_OUTPUT"
            fi

  publish_release:
    name: Publish Release ${{ github.ref_name }}
    needs: [get_metadata]
    runs-on: ubuntu-latest
    steps:
      - name: Publish Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.ref_name }}
          prerelease: ${{ needs.get_metadata.outputs.prerelease }}
