name: Release

on:
    workflow_dispatch:
        inputs:
            release_version:
                type: string
                description: The version to release
                required: true
            
            prerelease:
                type: boolean
                description: Mark release as pre-release
                default: false

jobs:
    build_cloudfront_logs_lambda:
        name: Build CloudFront Logs Lambda for Node.js v${{ matrix.nodejs_version }}.x
        runs-on: ubuntu-latest

        strategy:
            matrix:
                nodejs_version: [14, 16, 18]

        steps:
            - uses: actions/checkout@v3
        
            - name: Install Dependencies
              run: make install-cloudfront-logs-lambda
            
            - name: Build Lambda
              run: make build-cloudfront-logs-lambda
            
            - name: Copy Lambda Asset
              run: cp modules/cloudfront-logs/lambda/dist/lambda.zip cloudfront-logs-package-${{ inputs.release_version }}-nodejs${{ matrix.nodejs_version }}.x.zip
            
            - name: Store Output Artifact
              uses: actions/upload-artifact@v3
              with:
                name: cloudfront-logs-packages
                path: cloudfront-logs-package-${{ inputs.release_version }}-nodejs${{ matrix.nodejs_version }}.x.zip
                if-no-files-found: error